export const metadata = {
  title: "Main title",
  description: "Generated by create next app",
};

export default function HomePage() {
  console.log(process.env.NEXTAUTH_SECRET);
  return <div>Hello</div>;
}
